

FROM nginx
MAINTAINER The Project D&K <jinkyun1210@gmail.com>

# ENV LC_ALL en_US.UTF-8

COPY ./index.html /usr/share/nginx/html/
# RUN chmod 755 /start.sh

# ENTRYPOIN ["/xx/sshd", "sshd"]
# CMD /start.sh
